/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sr_alocuidador.views;

import br.com.sr_alocuidador.views.administracao.frmUsuarioPesq;
import br.com.sr_alocuidador.views.cadastros.frmCategoriaDoencaPesq;
import br.com.sr_alocuidador.views.cadastros.frmCategoriaPerguntaPesq;
import br.com.sr_alocuidador.views.cadastros.frmConvenioPesq;
import br.com.sr_alocuidador.views.cadastros.frmDoencaPesq;
import br.com.sr_alocuidador.views.cadastros.frmHospitalPesq;
import br.com.sr_alocuidador.views.cadastros.frmPerguntaPesq;
import br.com.sr_alocuidador.views.cadastros.frmServicoMedicoPesq;
import br.com.sr_alocuidador.views.cadastros.frmVacinaPesq;
import br.com.sr_alocuidador.views.movimentacao.frmPacientePesq;

/**
 *
 * @author Pablo
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        mnCategoriaDoenca = new javax.swing.JMenuItem();
        mnDoenca = new javax.swing.JMenuItem();
        mnConvenio = new javax.swing.JMenuItem();
        mnHospital = new javax.swing.JMenuItem();
        mnServicoMedico = new javax.swing.JMenuItem();
        mnVacina = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnCategoriaPergunta = new javax.swing.JMenuItem();
        mnPerguntas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnPaciente = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alô Cuidador");
        setExtendedState(MAXIMIZED_BOTH);

        jMenu1.setText("Cadastros");

        jMenu4.setText("Doenças");

        mnCategoriaDoenca.setText("Categoria");
        mnCategoriaDoenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCategoriaDoencaActionPerformed(evt);
            }
        });
        jMenu4.add(mnCategoriaDoenca);

        mnDoenca.setText("Doença");
        mnDoenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDoencaActionPerformed(evt);
            }
        });
        jMenu4.add(mnDoenca);

        jMenu1.add(jMenu4);

        mnConvenio.setText("Convênios");
        mnConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConvenioActionPerformed(evt);
            }
        });
        jMenu1.add(mnConvenio);

        mnHospital.setText("Hospitais");
        mnHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnHospitalActionPerformed(evt);
            }
        });
        jMenu1.add(mnHospital);

        mnServicoMedico.setText("Serviços Médicos");
        mnServicoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnServicoMedicoActionPerformed(evt);
            }
        });
        jMenu1.add(mnServicoMedico);

        mnVacina.setText("Vacinas");
        mnVacina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVacinaActionPerformed(evt);
            }
        });
        jMenu1.add(mnVacina);

        jMenu3.setText("Perguntas");

        mnCategoriaPergunta.setText("Categorias");
        mnCategoriaPergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCategoriaPerguntaActionPerformed(evt);
            }
        });
        jMenu3.add(mnCategoriaPergunta);

        mnPerguntas.setText("Perguntas");
        mnPerguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPerguntasActionPerformed(evt);
            }
        });
        jMenu3.add(mnPerguntas);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movimentação");

        mnPaciente.setText("Pacientes");
        mnPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPacienteActionPerformed(evt);
            }
        });
        jMenu2.add(mnPaciente);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Administração");

        mnUsuario.setText("Usuários");
        mnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUsuarioActionPerformed(evt);
            }
        });
        jMenu5.add(mnUsuario);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPacienteActionPerformed
        frmPacientePesq f = new frmPacientePesq(null, rootPaneCheckingEnabled);
        f.setVisible(true);
    }//GEN-LAST:event_mnPacienteActionPerformed

    private void mnCategoriaPerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCategoriaPerguntaActionPerformed
        frmCategoriaPerguntaPesq f = new frmCategoriaPerguntaPesq(null, rootPaneCheckingEnabled);
        f.setVisible(true);
    }//GEN-LAST:event_mnCategoriaPerguntaActionPerformed

    private void mnCategoriaDoencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCategoriaDoencaActionPerformed
        frmCategoriaDoencaPesq f = new frmCategoriaDoencaPesq(null, rootPaneCheckingEnabled);
        f.setVisible(true);
    }//GEN-LAST:event_mnCategoriaDoencaActionPerformed

    private void mnDoencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDoencaActionPerformed
        frmDoencaPesq f = new frmDoencaPesq(null, rootPaneCheckingEnabled);
        f.setVisible(true);
    }//GEN-LAST:event_mnDoencaActionPerformed

    private void mnServicoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnServicoMedicoActionPerformed
        frmServicoMedicoPesq f = new frmServicoMedicoPesq(null, rootPaneCheckingEnabled);
        f.setVisible(true);
    }//GEN-LAST:event_mnServicoMedicoActionPerformed

    private void mnVacinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVacinaActionPerformed
        frmVacinaPesq f = new frmVacinaPesq(null, rootPaneCheckingEnabled);
        f.setVisible(true);
    }//GEN-LAST:event_mnVacinaActionPerformed

    private void mnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUsuarioActionPerformed
        frmUsuarioPesq f = new frmUsuarioPesq(null, rootPaneCheckingEnabled);
        f.setVisible(true);
    }//GEN-LAST:event_mnUsuarioActionPerformed

    private void mnConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConvenioActionPerformed
        frmConvenioPesq f = new frmConvenioPesq(null, rootPaneCheckingEnabled);
        f.setVisible(true);
    }//GEN-LAST:event_mnConvenioActionPerformed

    private void mnHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnHospitalActionPerformed
        frmHospitalPesq f = new frmHospitalPesq(null, rootPaneCheckingEnabled);
        f.setVisible(true);
    }//GEN-LAST:event_mnHospitalActionPerformed

    private void mnPerguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPerguntasActionPerformed
        frmPerguntaPesq f = new frmPerguntaPesq(null, rootPaneCheckingEnabled);
        f.setVisible(true);
    }//GEN-LAST:event_mnPerguntasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnCategoriaDoenca;
    private javax.swing.JMenuItem mnCategoriaPergunta;
    private javax.swing.JMenuItem mnConvenio;
    private javax.swing.JMenuItem mnDoenca;
    private javax.swing.JMenuItem mnHospital;
    private javax.swing.JMenuItem mnPaciente;
    private javax.swing.JMenuItem mnPerguntas;
    private javax.swing.JMenuItem mnServicoMedico;
    private javax.swing.JMenuItem mnUsuario;
    private javax.swing.JMenuItem mnVacina;
    // End of variables declaration//GEN-END:variables
}
