/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sr_alocuidador.views.movimentacao;

import br.com.sr_alocuidador.daos.LigacaoExtraDAO;
import br.com.sr_alocuidador.helpers.VariaveisGlobais;
import br.com.sr_alocuidador.models.LigacaoExtra;
import br.com.sr_alocuidador.models.Paciente;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author plima
 */
public class frmPacienteLigacaoExtraCad extends javax.swing.JDialog {

    private LigacaoExtraDAO daoLigacaoExtra;
    
    public int xcodigo;
    public Paciente xpaciente;    
    
    public frmPacienteLigacaoExtraCad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTipo = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        lblAtendente = new javax.swing.JLabel();
        txtAtendente = new javax.swing.JTextField();
        lblMotivo = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        btnGravar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ligações Extras");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTipo.setText("Tipo:");
        getContentPane().add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "RETORNO", "DEPRESSÃO", "INTERNAÇÃO", "HIPERTENSÃO", "DIABETES" }));
        getContentPane().add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 350, -1));

        lblAtendente.setText("Atendente:");
        getContentPane().add(lblAtendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        getContentPane().add(txtAtendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 350, -1));

        lblMotivo.setText("Motivo:");
        getContentPane().add(lblMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        getContentPane().add(txtMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 350, -1));

        lblDescricao.setText("Descrição:");
        getContentPane().add(lblDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 630, -1));

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        setSize(new java.awt.Dimension(672, 393));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        daoLigacaoExtra = new LigacaoExtraDAO();
        try {
            pesquisar();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro encontrado: " + ex.toString());
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        if (validaDados()){
            try {
                gravar();
                JOptionPane.showMessageDialog(null, "Registro gravado com sucesso.");
                this.setVisible(false);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao gravar o registro: "  + ex.toString());
            }
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPacienteLigacaoExtraCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPacienteLigacaoExtraCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPacienteLigacaoExtraCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPacienteLigacaoExtraCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPacienteLigacaoExtraCad dialog = new frmPacienteLigacaoExtraCad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGravar;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAtendente;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtAtendente;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtMotivo;
    // End of variables declaration//GEN-END:variables

    private boolean validaDados(){
        
        if (cmbTipo.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Tipo não informado.");
            return false;
        } else if ("".equals(txtAtendente.getText())){
            JOptionPane.showMessageDialog(null, "Atendente não informado.");
            return false;
        } else if ("".equals(txtMotivo.getText())){
            JOptionPane.showMessageDialog(null, "Motivo não informado.");
            return false;
        } else if ("".equals(txtDescricao.getText())){
            JOptionPane.showMessageDialog(null, "Descrição não informada.");
            return false;
        } else return true;        
        
    }
    
    private void gravar() throws SQLException{
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        Date data = new Date();
        
        LigacaoExtra c = new LigacaoExtra();
        c.setCodigo(xcodigo);
        c.setPaciente(xpaciente);
        c.setData(formato.format(data));
        c.setMotivo(txtMotivo.getText());
        c.setDescricao(txtDescricao.getText());
        c.setUsuario(VariaveisGlobais.getInstance().getDadosUsuario());
        c.setAtendente(txtAtendente.getText());
        switch (cmbTipo.getSelectedIndex()) {
            case 1:
                c.setTipo("RET");
                break;
            case 2:
                c.setTipo("DEP");
                break;
            case 3:
                c.setTipo("INT");
                break;
            case 4:
                c.setTipo("HIP");
                break;
            case 5:
                c.setTipo("DIA");
                break;
            default:
                break;
        }
        daoLigacaoExtra.incluir(c);        
    }
    
    private void pesquisar() throws SQLException {
        LigacaoExtra c = daoLigacaoExtra.buscarPorId(xcodigo);
        if (c != null){
            if (null == c.getTipo())
                cmbTipo.setSelectedIndex(0);
            else switch (c.getTipo()) {
                case "RET":
                    cmbTipo.setSelectedIndex(1);
                    break;
                case "DEP":
                    cmbTipo.setSelectedIndex(2);
                    break;
                case "INT":
                    cmbTipo.setSelectedIndex(3);
                    break;
                case "HIP":
                    cmbTipo.setSelectedIndex(4);
                    break;
                case "DIA":
                    cmbTipo.setSelectedIndex(5);
                    break;
                default:
                    cmbTipo.setSelectedIndex(0);
                    break;
            }
            
            txtAtendente.setText(c.getAtendente());
            txtMotivo.setText(c.getMotivo());
            txtDescricao.setText(c.getDescricao());
        }
    }
    
}
