/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sr_alocuidador.views.movimentacao;

import br.com.sr_alocuidador.daos.ConvenioDAO;
import br.com.sr_alocuidador.daos.PacienteDAO;
import br.com.sr_alocuidador.daos.PacienteInternacaoDAO;
import br.com.sr_alocuidador.helpers.JtextFieldSomenteNumeros;
import br.com.sr_alocuidador.helpers.Uteis;
import br.com.sr_alocuidador.models.Convenio;
import br.com.sr_alocuidador.models.Paciente;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author plima
 */
public class frmPacienteCad extends javax.swing.JDialog {

    // Variaveis de inicialização
    public int xcodigo;
    private PacienteDAO daoPaciente;
    private List<Convenio> listarConvenios;
    private PacienteInternacaoDAO daoPacienteInternacao;

    /**
     * Creates new form frmPacienteCad
     */
    public frmPacienteCad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlDadosPessoais = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblApelido = new javax.swing.JLabel();
        txtApelido = new javax.swing.JTextField();
        lblNascimento = new javax.swing.JLabel();
        txtNascimento = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox<>();
        lblEstadoCivil = new javax.swing.JLabel();
        cmbEstadoCivil = new javax.swing.JComboBox<>();
        lblEscolaridade = new javax.swing.JLabel();
        cmbEscolaridade = new javax.swing.JComboBox<>();
        lblConjuge = new javax.swing.JLabel();
        txtConjuge = new javax.swing.JTextField();
        lblConvenio = new javax.swing.JLabel();
        cmbConvenio = new javax.swing.JComboBox<>();
        cbxAph = new javax.swing.JCheckBox();
        lblMatricula = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblUf = new javax.swing.JLabel();
        txtUf = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        lblFone = new javax.swing.JLabel();
        txtFoneFixo = new javax.swing.JTextField();
        lblFoneCelular = new javax.swing.JLabel();
        txtFoneCelular = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblAnimalEstimacao = new javax.swing.JLabel();
        txtAnimalEstimacao = new javax.swing.JTextField();
        lblHobby = new javax.swing.JLabel();
        txtHobby = new javax.swing.JTextField();
        lblNivelCategoria = new javax.swing.JLabel();
        cmbNivelCategoria = new javax.swing.JComboBox<>();
        lblIntervalo = new javax.swing.JLabel();
        txtIntervalo = new JtextFieldSomenteNumeros();
        lblLace = new javax.swing.JLabel();
        txtIndiceLace = new javax.swing.JTextField();
        pnlOutrosDados = new javax.swing.JPanel();
        lblAlergia = new javax.swing.JLabel();
        txtAlergia = new javax.swing.JTextField();
        pnlAlimentacao = new javax.swing.JPanel();
        cmbAlimentacao = new javax.swing.JComboBox<>();
        lblAlimentacaoEnteral = new javax.swing.JLabel();
        cmbAlimentacaoEnteral = new javax.swing.JComboBox<>();
        lblAlimentacaoTipo = new javax.swing.JLabel();
        cmbAlimentacaoTipo = new javax.swing.JComboBox<>();
        pnlIngestaoAlimentacao = new javax.swing.JPanel();
        lblSalgado = new javax.swing.JLabel();
        cmbSalgado = new javax.swing.JComboBox<>();
        lblConservas = new javax.swing.JLabel();
        cmbConservas = new javax.swing.JComboBox<>();
        lblEnlatado = new javax.swing.JLabel();
        cmbEnlatado = new javax.swing.JComboBox<>();
        lblIndustrializados = new javax.swing.JLabel();
        cmbIndustrializado = new javax.swing.JComboBox<>();
        lblSaleiro = new javax.swing.JLabel();
        cmbSaleiro = new javax.swing.JComboBox<>();
        lblDiurese = new javax.swing.JLabel();
        cmbDiurese = new javax.swing.JComboBox<>();
        cbxFralda = new javax.swing.JCheckBox();
        lblEliminacaoIntestinal = new javax.swing.JLabel();
        cmbEliminacaoIntestinal = new javax.swing.JComboBox<>();
        lblSuporteOxigenio = new javax.swing.JLabel();
        cmbSuporteOxigenio = new javax.swing.JComboBox<>();
        lblLesaoPele = new javax.swing.JLabel();
        cmbLesaoPele = new javax.swing.JComboBox<>();
        lblHistoricoQueda = new javax.swing.JLabel();
        cmbHistoricoQueda = new javax.swing.JComboBox<>();
        cbxFratura = new javax.swing.JCheckBox();
        cbxAntibiotico = new javax.swing.JCheckBox();
        lblCircunferenciaAbdominal = new javax.swing.JLabel();
        txtCircunferenciaAbdominal = new JtextFieldSomenteNumeros();
        lblGlicemiaJejum = new javax.swing.JLabel();
        txtGlicemiaJejum = new JtextFieldSomenteNumeros();
        pnlAtividadeFisica = new javax.swing.JPanel();
        cmbAtividadeFisica = new javax.swing.JComboBox<>();
        lblTipoAtividadeFisica = new javax.swing.JLabel();
        cmbAtividadeFisicaTipo = new javax.swing.JComboBox<>();
        lblHabitoAlimentar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHabitoAlimentar = new javax.swing.JTextArea();
        lblIngestaHidrica = new javax.swing.JLabel();
        cmbIngestaHidrica = new javax.swing.JComboBox<>();
        pnlMobilidade1 = new javax.swing.JPanel();
        cmbMobilidade = new javax.swing.JComboBox<>();
        lblMobilidadeAcamado1 = new javax.swing.JLabel();
        cmbMobilidadeAcamado = new javax.swing.JComboBox<>();
        lblDenticao = new javax.swing.JLabel();
        cmbDenticao = new javax.swing.JComboBox<>();
        lblAcuidadeVisual = new javax.swing.JLabel();
        cmbAcuidadeVisual = new javax.swing.JComboBox<>();
        lblAcuidadeAuditiva = new javax.swing.JLabel();
        cmbAcuidadeAuditiva = new javax.swing.JComboBox<>();
        pnlNiveis = new javax.swing.JPanel();
        cmbNivelConsciencia = new javax.swing.JComboBox<>();
        lblNivelConsciencia = new javax.swing.JLabel();
        lblNivelOrientacao = new javax.swing.JLabel();
        cmbNivelOrientacao = new javax.swing.JComboBox<>();
        cmbNivelDependencia = new javax.swing.JComboBox<>();
        lblNivelDependencia = new javax.swing.JLabel();
        pnlImc = new javax.swing.JPanel();
        lblPeso = new javax.swing.JLabel();
        txtPeso = new JtextFieldSomenteNumeros();
        lblAltura = new javax.swing.JLabel();
        txtAltura = new JtextFieldSomenteNumeros();
        lblIMC = new javax.swing.JLabel();
        txtIMC = new javax.swing.JTextField();
        pnlColesterol = new javax.swing.JPanel();
        lblLDL = new javax.swing.JLabel();
        txtLDL = new javax.swing.JTextField();
        lblHDL = new javax.swing.JLabel();
        txtHDL = new javax.swing.JTextField();
        lblTriglicerideos = new javax.swing.JLabel();
        txtTriglicerideos = new javax.swing.JTextField();
        lblColesterolTotal = new javax.swing.JLabel();
        txtColesterolTotal = new javax.swing.JTextField();
        lblTabagismo = new javax.swing.JLabel();
        cmbTabagismo = new javax.swing.JComboBox<>();
        lblAlcoolismo = new javax.swing.JLabel();
        cmbAlcoolismo = new javax.swing.JComboBox<>();
        lblConsumoAlcool = new javax.swing.JLabel();
        cmbConsumoAlcool = new javax.swing.JComboBox<>();
        btnGravar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pacientes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlDadosPessoais.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setText("Nome:");
        pnlDadosPessoais.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        pnlDadosPessoais.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 340, -1));

        lblApelido.setText("Apelido:");
        pnlDadosPessoais.add(lblApelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));
        pnlDadosPessoais.add(txtApelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 170, -1));

        lblNascimento.setText("Nascimento:");
        pnlDadosPessoais.add(lblNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));
        pnlDadosPessoais.add(txtNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 110, -1));

        lblSexo.setText("Sexo:");
        pnlDadosPessoais.add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "MASCULINO", "FEMININO" }));
        pnlDadosPessoais.add(cmbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 120, -1));

        lblEstadoCivil.setText("Estado Civil:");
        pnlDadosPessoais.add(lblEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        cmbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "SOLTEIRO(A)", "CASADO(A)", "VIÚVO(A)", "SEPARADO(A)", "OUTROS" }));
        pnlDadosPessoais.add(cmbEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 160, -1));

        lblEscolaridade.setText("Escolaridade:");
        pnlDadosPessoais.add(lblEscolaridade, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, -1, -1));

        cmbEscolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO INFORMADO", "FUNDAMENTAL", "MÉDIO", "SUPERIOR", "SEM ESCOLARIDADE" }));
        pnlDadosPessoais.add(cmbEscolaridade, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, 160, -1));

        lblConjuge.setText("Cônjuge:");
        pnlDadosPessoais.add(lblConjuge, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        pnlDadosPessoais.add(txtConjuge, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 210, -1));

        lblConvenio.setText("Convênio:");
        pnlDadosPessoais.add(lblConvenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        cmbConvenio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlDadosPessoais.add(cmbConvenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 260, -1));

        cbxAph.setText("Possui APH");
        pnlDadosPessoais.add(cbxAph, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        lblMatricula.setText("Matricula:");
        pnlDadosPessoais.add(lblMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, -1, -1));
        pnlDadosPessoais.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 140, -1));

        lblEndereco.setText("Endereço:");
        pnlDadosPessoais.add(lblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        pnlDadosPessoais.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 410, -1));

        lblBairro.setText("Bairro:");
        pnlDadosPessoais.add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));
        pnlDadosPessoais.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 270, -1));

        lblCidade.setText("Cidade:");
        pnlDadosPessoais.add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, -1, -1));
        pnlDadosPessoais.add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 210, -1));

        lblUf.setText("UF:");
        pnlDadosPessoais.add(lblUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, -1, -1));
        pnlDadosPessoais.add(txtUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 130, 60, -1));

        lblCep.setText("CEP:");
        pnlDadosPessoais.add(lblCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 110, -1, -1));
        pnlDadosPessoais.add(txtCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 130, 100, -1));

        lblFone.setText("Telefone Fixo:");
        pnlDadosPessoais.add(lblFone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        pnlDadosPessoais.add(txtFoneFixo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 300, -1));

        lblFoneCelular.setText("Telefone Celular:");
        pnlDadosPessoais.add(lblFoneCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));
        pnlDadosPessoais.add(txtFoneCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 300, -1));

        lblEmail.setText("Email:");
        pnlDadosPessoais.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));
        pnlDadosPessoais.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 300, -1));

        lblAnimalEstimacao.setText("Animal de Estimação:");
        pnlDadosPessoais.add(lblAnimalEstimacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 160, -1, -1));
        pnlDadosPessoais.add(txtAnimalEstimacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 180, 160, -1));

        lblHobby.setText("Hobby:");
        pnlDadosPessoais.add(lblHobby, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 160, -1, -1));
        pnlDadosPessoais.add(txtHobby, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 180, 160, -1));

        lblNivelCategoria.setText("Nível/Categoria:");
        pnlDadosPessoais.add(lblNivelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        cmbNivelCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO INFORMADO", "NÍVEL 1 - CONTROLE", "NÍVEL 2 - TESTE", "NÍVEL 3 - INTERIOR" }));
        pnlDadosPessoais.add(cmbNivelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 180, -1));

        lblIntervalo.setText("Intervalo:");
        pnlDadosPessoais.add(lblIntervalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        txtIntervalo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pnlDadosPessoais.add(txtIntervalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 80, -1));

        lblLace.setText("Índice de Lace:");
        pnlDadosPessoais.add(lblLace, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        txtIndiceLace.setEditable(false);
        txtIndiceLace.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pnlDadosPessoais.add(txtIndiceLace, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 80, -1));

        jTabbedPane1.addTab("Dados Pessoais", pnlDadosPessoais);

        pnlOutrosDados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAlergia.setText("Alergia:");
        pnlOutrosDados.add(lblAlergia, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));
        pnlOutrosDados.add(txtAlergia, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 140, -1));

        pnlAlimentacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Alimentação"));
        pnlAlimentacao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbAlimentacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO INFORMADO", "ORAL", "ENTERAL" }));
        pnlAlimentacao.add(cmbAlimentacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, -1));

        lblAlimentacaoEnteral.setText("Se alimentação Enteral:");
        pnlAlimentacao.add(lblAlimentacaoEnteral, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        cmbAlimentacaoEnteral.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO INFORMADO", "CNE", "CNG", "GTT", "CJT" }));
        pnlAlimentacao.add(cmbAlimentacaoEnteral, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, -1));

        lblAlimentacaoTipo.setText("Tipo:");
        pnlAlimentacao.add(lblAlimentacaoTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        cmbAlimentacaoTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO INFORMADO", "CASEIRA", "ARTESANAL" }));
        pnlAlimentacao.add(cmbAlimentacaoTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, -1));

        pnlIngestaoAlimentacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Costuma Ingerir Alimentos"));
        pnlIngestaoAlimentacao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSalgado.setText("Salgados:");
        pnlIngestaoAlimentacao.add(lblSalgado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        cmbSalgado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIM", "NÃO", "RECUSA", "NÃO INFORMADO" }));
        pnlIngestaoAlimentacao.add(cmbSalgado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, -1));

        lblConservas.setText("Conservas:");
        pnlIngestaoAlimentacao.add(lblConservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        cmbConservas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIM", "NÃO", "RECUSA", "NÃO INFORMADO" }));
        pnlIngestaoAlimentacao.add(cmbConservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 120, -1));

        lblEnlatado.setText("Enlatados:");
        pnlIngestaoAlimentacao.add(lblEnlatado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        cmbEnlatado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIM", "NÃO", "RECUSA", "NÃO INFORMADO" }));
        pnlIngestaoAlimentacao.add(cmbEnlatado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, -1));

        lblIndustrializados.setText("Industrializados:");
        pnlIngestaoAlimentacao.add(lblIndustrializados, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        cmbIndustrializado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIM", "NÃO", "RECUSA", "NÃO INFORMADO" }));
        pnlIngestaoAlimentacao.add(cmbIndustrializado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 120, -1));

        lblSaleiro.setText("Usa saleiro na mesa:");
        pnlIngestaoAlimentacao.add(lblSaleiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        cmbSaleiro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIM", "NÃO", "RECUSA", "NÃO INFORMADO" }));
        pnlIngestaoAlimentacao.add(cmbSaleiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, -1));

        pnlAlimentacao.add(pnlIngestaoAlimentacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 270, 170));

        pnlOutrosDados.add(pnlAlimentacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 440, 190));

        lblDiurese.setText("Diurese:");
        pnlOutrosDados.add(lblDiurese, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, -1, -1));

        cmbDiurese.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO INFORMADO", "ESPONTÂNEA", "INCONTINÊNCIA", "CATETERISMO VESICAL DE ALIVIO", "CATETERISMO VESICAL DE DEMORA" }));
        pnlOutrosDados.add(cmbDiurese, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 220, -1));

        cbxFralda.setText("Usa Fralda");
        pnlOutrosDados.add(cbxFralda, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        lblEliminacaoIntestinal.setText("Eliminações Intestinais:");
        pnlOutrosDados.add(lblEliminacaoIntestinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, -1));

        cmbEliminacaoIntestinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO INFORMADO", "PRESERVADAS", "CONSTIPAÇÃO", "DIARRÉIA", "INCONTINÊNCIA", "COLOSTOMIA" }));
        pnlOutrosDados.add(cmbEliminacaoIntestinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 130, -1));

        lblSuporteOxigenio.setText("Suporte de Oxigênio:");
        pnlOutrosDados.add(lblSuporteOxigenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        cmbSuporteOxigenio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO INFORMADO", "CILINDRO", "CONCENTRADOR", "CATETER NASAL", "MÁSCARA DE VENTURI" }));
        pnlOutrosDados.add(cmbSuporteOxigenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 160, -1));

        lblLesaoPele.setText("Lesões de Pele:");
        pnlOutrosDados.add(lblLesaoPele, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        cmbLesaoPele.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO INFORMADO", "ESTAGIO I", "ESTAGIO II", "ESTAGIO III", "ESTAGIO IV" }));
        pnlOutrosDados.add(cmbLesaoPele, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 160, -1));

        lblHistoricoQueda.setText("Histório de Queda:");
        pnlOutrosDados.add(lblHistoricoQueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        cmbHistoricoQueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO INFORMADO", "RECENTE", "EVENTUAL" }));
        pnlOutrosDados.add(cmbHistoricoQueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 160, -1));

        cbxFratura.setText("Fratura?");
        pnlOutrosDados.add(cbxFratura, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, -1, -1));

        cbxAntibiotico.setText("Uso de antibiótico");
        pnlOutrosDados.add(cbxAntibiotico, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, -1, -1));

        lblCircunferenciaAbdominal.setText("Circunferência Abdominal:");
        pnlOutrosDados.add(lblCircunferenciaAbdominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, -1, -1));
        pnlOutrosDados.add(txtCircunferenciaAbdominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 130, -1));

        lblGlicemiaJejum.setText("Glicemia em jejum:");
        pnlOutrosDados.add(lblGlicemiaJejum, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 200, -1, -1));
        pnlOutrosDados.add(txtGlicemiaJejum, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 220, 130, -1));

        pnlAtividadeFisica.setBorder(javax.swing.BorderFactory.createTitledBorder("Atividade Física:"));
        pnlAtividadeFisica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbAtividadeFisica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO INFORMADO", "SEDENTÁRIO", "IRREGULAR", "REGULAR" }));
        pnlAtividadeFisica.add(cmbAtividadeFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 300, -1));

        lblTipoAtividadeFisica.setText("Tipo:");
        pnlAtividadeFisica.add(lblTipoAtividadeFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        cmbAtividadeFisicaTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO INFORMADO", "BALET", "BASQUETE", "BOXE", "CAMINHADA", "CAPOEIRA", "CICLISMO", "CORRIDA", "DANÇA", "FUTEBOL", "FUTSAL", "HANDEBOL", "JIU JITSU", "JUDÔ", "KARATÊ", "MMA", "MOTOCROSS", "MUAY THAI", "MUSCULAÇÃO", "NATAÇÃO", "PATINAÇÃO", "SKATE", "SURF", "TÊNIS", "TRIATLON", "TRILHA", "VOLEIBOL" }));
        pnlAtividadeFisica.add(cmbAtividadeFisicaTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 300, -1));

        pnlOutrosDados.add(pnlAtividadeFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 330, 100));

        lblHabitoAlimentar.setText("Hábito Alimentar:");
        pnlOutrosDados.add(lblHabitoAlimentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, 110, -1));

        txtHabitoAlimentar.setColumns(20);
        txtHabitoAlimentar.setRows(5);
        jScrollPane1.setViewportView(txtHabitoAlimentar);

        pnlOutrosDados.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, 440, 100));

        lblIngestaHidrica.setText("Ingesta Hídrica:");
        pnlOutrosDados.add(lblIngestaHidrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        cmbIngestaHidrica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO INFORMADO", "ADEQUADA", "DEFICIENTE" }));
        pnlOutrosDados.add(cmbIngestaHidrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 160, -1));

        pnlMobilidade1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mobilidade:"));
        pnlMobilidade1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbMobilidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO INFORMADO", "ACAMADO", "COM AJUDA", "USO DE ÓSTESE/PRÓTESE" }));
        pnlMobilidade1.add(cmbMobilidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, -1));

        lblMobilidadeAcamado1.setText("Se Acamado:");
        pnlMobilidade1.add(lblMobilidadeAcamado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        cmbMobilidadeAcamado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO INFORMADO", "CAMA COMUM", "CAMA HOSPITALAR" }));
        pnlMobilidade1.add(cmbMobilidadeAcamado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, -1));

        pnlOutrosDados.add(pnlMobilidade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 200, 200, 100));

        lblDenticao.setText("Dentição:");
        pnlOutrosDados.add(lblDenticao, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        cmbDenticao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO INFORMADO", "PRESERVADA", "PRÓTESE FÍSICA PARCIAL", "PRÓTESE FÍSICA TOTAL", "PRÓTESE REMOVÍVEL PARCIAL", "PRÓTESE REMOVÍVEL TOTAL" }));
        pnlOutrosDados.add(cmbDenticao, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 230, -1));

        lblAcuidadeVisual.setText("Acuidade Visual:");
        pnlOutrosDados.add(lblAcuidadeVisual, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        cmbAcuidadeVisual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO INFORMADO", "NORMAL", "DIMINUIDA", "USO DE LENTES CORRETIVAS" }));
        pnlOutrosDados.add(cmbAcuidadeVisual, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 230, -1));

        lblAcuidadeAuditiva.setText("Acuidade Auditiva:");
        pnlOutrosDados.add(lblAcuidadeAuditiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, -1));

        cmbAcuidadeAuditiva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO INFORMADO", "NORMAL", "DIMINUIDA", "USO DE APARELHO AUDITIVO" }));
        pnlOutrosDados.add(cmbAcuidadeAuditiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 230, -1));

        pnlNiveis.setBorder(javax.swing.BorderFactory.createTitledBorder("Níveis"));
        pnlNiveis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbNivelConsciencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO INFORMADO", "CONSCIENTE", "INCONSCIENTE" }));
        pnlNiveis.add(cmbNivelConsciencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, -1));

        lblNivelConsciencia.setText("Consciência:");
        pnlNiveis.add(lblNivelConsciencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblNivelOrientacao.setText("Nível de Orientação:");
        pnlNiveis.add(lblNivelOrientacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        cmbNivelOrientacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO INFORMADO", "ORIENTADO", "DESORIENTADO" }));
        pnlNiveis.add(cmbNivelOrientacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, -1));

        cmbNivelDependencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO INFORMADO", "INDEPENDENTE", "DEPENDENCIA MODERADA", "MUITO DEPENDENTE" }));
        pnlNiveis.add(cmbNivelDependencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 180, -1));

        lblNivelDependencia.setText("Nível de Dependência:");
        pnlNiveis.add(lblNivelDependencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        pnlOutrosDados.add(pnlNiveis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 170));

        pnlImc.setBorder(javax.swing.BorderFactory.createTitledBorder("IMC"));
        pnlImc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPeso.setText("Peso:");
        pnlImc.add(lblPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        pnlImc.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, -1));

        lblAltura.setText("Altura:");
        pnlImc.add(lblAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        pnlImc.add(txtAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, -1));

        lblIMC.setText("IMC:");
        pnlImc.add(lblIMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txtIMC.setEditable(false);
        pnlImc.add(txtIMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 150, -1));

        pnlOutrosDados.add(pnlImc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 170, 170));

        pnlColesterol.setBorder(javax.swing.BorderFactory.createTitledBorder("Colesterol"));
        pnlColesterol.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLDL.setText("LDL:");
        pnlColesterol.add(lblLDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        pnlColesterol.add(txtLDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, -1));

        lblHDL.setText("HDL:");
        pnlColesterol.add(lblHDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));
        pnlColesterol.add(txtHDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 80, -1));

        lblTriglicerideos.setText("Triglicerídeos:");
        pnlColesterol.add(lblTriglicerideos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        pnlColesterol.add(txtTriglicerideos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, -1));

        lblColesterolTotal.setText("Colesterol Total:");
        pnlColesterol.add(lblColesterolTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));
        pnlColesterol.add(txtColesterolTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 80, -1));

        pnlOutrosDados.add(pnlColesterol, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 190, 170));

        lblTabagismo.setText("Tabagismo:");
        pnlOutrosDados.add(lblTabagismo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        cmbTabagismo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIM", "NÃO", "RECUSA", "NÃO INFORMADO" }));
        pnlOutrosDados.add(cmbTabagismo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 140, -1));

        lblAlcoolismo.setText("Alcoolismo:");
        pnlOutrosDados.add(lblAlcoolismo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        cmbAlcoolismo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIM", "NÃO", "RECUSA", "NÃO INFORMADO" }));
        pnlOutrosDados.add(cmbAlcoolismo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 140, -1));

        lblConsumoAlcool.setText("Consumo de Álcool:");
        pnlOutrosDados.add(lblConsumoAlcool, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

        cmbConsumoAlcool.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIM", "NÃO", "RECUSA", "NÃO INFORMADO" }));
        pnlOutrosDados.add(cmbConsumoAlcool, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 140, -1));

        jTabbedPane1.addTab("Outros Dados", pnlOutrosDados);

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGravar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnGravar)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1333, 576));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        daoPaciente = new PacienteDAO();
        daoPacienteInternacao = new PacienteInternacaoDAO();
        try {
            PreencheConvenio();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro de sql: " + ex.toString());
        }
        Pesquisar();
    }//GEN-LAST:event_formWindowOpened

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        if (validaDados()) {
            try{
                gravar();
                JOptionPane.showMessageDialog(null, "Registro gravado com sucesso.");
                this.setVisible(false);
            } catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Erro encontrado: " + ex.toString());
            }
        }

    }//GEN-LAST:event_btnGravarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPacienteCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPacienteCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPacienteCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPacienteCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPacienteCad dialog = new frmPacienteCad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGravar;
    private javax.swing.JCheckBox cbxAntibiotico;
    private javax.swing.JCheckBox cbxAph;
    private javax.swing.JCheckBox cbxFralda;
    private javax.swing.JCheckBox cbxFratura;
    private javax.swing.JComboBox<String> cmbAcuidadeAuditiva;
    private javax.swing.JComboBox<String> cmbAcuidadeVisual;
    private javax.swing.JComboBox<String> cmbAlcoolismo;
    private javax.swing.JComboBox<String> cmbAlimentacao;
    private javax.swing.JComboBox<String> cmbAlimentacaoEnteral;
    private javax.swing.JComboBox<String> cmbAlimentacaoTipo;
    private javax.swing.JComboBox<String> cmbAtividadeFisica;
    private javax.swing.JComboBox<String> cmbAtividadeFisicaTipo;
    private javax.swing.JComboBox<String> cmbConservas;
    private javax.swing.JComboBox<String> cmbConsumoAlcool;
    private javax.swing.JComboBox<Object> cmbConvenio;
    private javax.swing.JComboBox<String> cmbDenticao;
    private javax.swing.JComboBox<String> cmbDiurese;
    private javax.swing.JComboBox<String> cmbEliminacaoIntestinal;
    private javax.swing.JComboBox<String> cmbEnlatado;
    private javax.swing.JComboBox<String> cmbEscolaridade;
    private javax.swing.JComboBox<String> cmbEstadoCivil;
    private javax.swing.JComboBox<String> cmbHistoricoQueda;
    private javax.swing.JComboBox<String> cmbIndustrializado;
    private javax.swing.JComboBox<String> cmbIngestaHidrica;
    private javax.swing.JComboBox<String> cmbLesaoPele;
    private javax.swing.JComboBox<String> cmbMobilidade;
    private javax.swing.JComboBox<String> cmbMobilidadeAcamado;
    private javax.swing.JComboBox<String> cmbNivelCategoria;
    private javax.swing.JComboBox<String> cmbNivelConsciencia;
    private javax.swing.JComboBox<String> cmbNivelDependencia;
    private javax.swing.JComboBox<String> cmbNivelOrientacao;
    private javax.swing.JComboBox<String> cmbSaleiro;
    private javax.swing.JComboBox<String> cmbSalgado;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JComboBox<String> cmbSuporteOxigenio;
    private javax.swing.JComboBox<String> cmbTabagismo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAcuidadeAuditiva;
    private javax.swing.JLabel lblAcuidadeVisual;
    private javax.swing.JLabel lblAlcoolismo;
    private javax.swing.JLabel lblAlergia;
    private javax.swing.JLabel lblAlimentacaoEnteral;
    private javax.swing.JLabel lblAlimentacaoTipo;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblAnimalEstimacao;
    private javax.swing.JLabel lblApelido;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCircunferenciaAbdominal;
    private javax.swing.JLabel lblColesterolTotal;
    private javax.swing.JLabel lblConjuge;
    private javax.swing.JLabel lblConservas;
    private javax.swing.JLabel lblConsumoAlcool;
    private javax.swing.JLabel lblConvenio;
    private javax.swing.JLabel lblDenticao;
    private javax.swing.JLabel lblDiurese;
    private javax.swing.JLabel lblEliminacaoIntestinal;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEnlatado;
    private javax.swing.JLabel lblEscolaridade;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblFone;
    private javax.swing.JLabel lblFoneCelular;
    private javax.swing.JLabel lblGlicemiaJejum;
    private javax.swing.JLabel lblHDL;
    private javax.swing.JLabel lblHabitoAlimentar;
    private javax.swing.JLabel lblHistoricoQueda;
    private javax.swing.JLabel lblHobby;
    private javax.swing.JLabel lblIMC;
    private javax.swing.JLabel lblIndustrializados;
    private javax.swing.JLabel lblIngestaHidrica;
    private javax.swing.JLabel lblIntervalo;
    private javax.swing.JLabel lblLDL;
    private javax.swing.JLabel lblLace;
    private javax.swing.JLabel lblLesaoPele;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblMobilidadeAcamado1;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNivelCategoria;
    private javax.swing.JLabel lblNivelConsciencia;
    private javax.swing.JLabel lblNivelDependencia;
    private javax.swing.JLabel lblNivelOrientacao;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblSaleiro;
    private javax.swing.JLabel lblSalgado;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblSuporteOxigenio;
    private javax.swing.JLabel lblTabagismo;
    private javax.swing.JLabel lblTipoAtividadeFisica;
    private javax.swing.JLabel lblTriglicerideos;
    private javax.swing.JLabel lblUf;
    private javax.swing.JPanel pnlAlimentacao;
    private javax.swing.JPanel pnlAtividadeFisica;
    private javax.swing.JPanel pnlColesterol;
    private javax.swing.JPanel pnlDadosPessoais;
    private javax.swing.JPanel pnlImc;
    private javax.swing.JPanel pnlIngestaoAlimentacao;
    private javax.swing.JPanel pnlMobilidade1;
    private javax.swing.JPanel pnlNiveis;
    private javax.swing.JPanel pnlOutrosDados;
    private javax.swing.JTextField txtAlergia;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtAnimalEstimacao;
    private javax.swing.JTextField txtApelido;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCircunferenciaAbdominal;
    private javax.swing.JTextField txtColesterolTotal;
    private javax.swing.JTextField txtConjuge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtFoneCelular;
    private javax.swing.JTextField txtFoneFixo;
    private javax.swing.JTextField txtGlicemiaJejum;
    private javax.swing.JTextField txtHDL;
    private javax.swing.JTextArea txtHabitoAlimentar;
    private javax.swing.JTextField txtHobby;
    private javax.swing.JTextField txtIMC;
    private javax.swing.JTextField txtIndiceLace;
    private javax.swing.JTextField txtIntervalo;
    private javax.swing.JTextField txtLDL;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtTriglicerideos;
    private javax.swing.JTextField txtUf;
    // End of variables declaration//GEN-END:variables

    private boolean validaDados() {
        if ("".equals(txtNome.getText())) {
            JOptionPane.showMessageDialog(null, "Nome não informado");
            jTabbedPane1.setSelectedIndex(0);
            txtNome.setFocusable(true);
            return false;
        } else if ("".equals(txtNascimento.getText())) {
            JOptionPane.showMessageDialog(null, "Data de nascimento não informado");
            jTabbedPane1.setSelectedIndex(0);
            txtNascimento.setFocusable(true);
            return false;
        } else if (cmbSexo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Sexo não informado");
            jTabbedPane1.setSelectedIndex(0);
            cmbSexo.setFocusable(true);
            return false;
        } else if (cmbEstadoCivil.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Estado civil não informado");
            jTabbedPane1.setSelectedIndex(0);
            cmbEstadoCivil.setFocusable(true);
            return false;
        } else if (cmbConvenio.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Convênio não informado");
            jTabbedPane1.setSelectedIndex(0);
            cmbConvenio.setFocusable(true);
            return false;
        } else if ("".equals(txtFoneFixo.getText())) {
            JOptionPane.showMessageDialog(null, "Telefone fixo não informado");
            jTabbedPane1.setSelectedIndex(0);
            txtFoneFixo.setFocusable(true);
            return false;
        } else if ("".equals(txtFoneCelular.getText())) {
            JOptionPane.showMessageDialog(null, "Celular fixo não informado");
            jTabbedPane1.setSelectedIndex(0);
            txtFoneCelular.setFocusable(true);
            return false;
        } else if ("".equals(txtEmail.getText())) {
            JOptionPane.showMessageDialog(null, "Email não informado");
            jTabbedPane1.setSelectedIndex(0);
            txtEmail.setFocusable(true);
            return false;
        } 
        else if ("".equals(txtPeso.getText())) {
            JOptionPane.showMessageDialog(null, "Peso não informado");
            jTabbedPane1.setSelectedIndex(1);
            txtPeso.setFocusable(true);
            return false;
        } 
        else if ("".equals(txtAltura.getText())) {
            JOptionPane.showMessageDialog(null, "Altura não informado");
            jTabbedPane1.setSelectedIndex(1);
            txtAltura.setFocusable(true);
            return false;
        }
        else if ("".equals(txtCircunferenciaAbdominal.getText())) {
            JOptionPane.showMessageDialog(null, "Circunferência abdominal não informado");
            jTabbedPane1.setSelectedIndex(1);
            txtCircunferenciaAbdominal.setFocusable(true);
            return false;
        }
        else if ("".equals(txtGlicemiaJejum.getText())) {
            JOptionPane.showMessageDialog(null, "Glicemia em jejum não informado");
            jTabbedPane1.setSelectedIndex(1);
            txtGlicemiaJejum.setFocusable(true);
            return false;
        }        
        else {
            return true;
        }
    }

    private void Pesquisar() {
        try {
            Paciente paciente = PacienteDAO.buscarPorId(xcodigo);
            if (paciente != null) {
                txtNome.setText(paciente.getNome());
                txtApelido.setText(paciente.getApelido());
                txtNascimento.setText(Uteis.formatarData(paciente.getNascimento()));
                cmbSexo.setSelectedIndex(paciente.getSexo());
                cmbEstadoCivil.setSelectedIndex(paciente.getEstadocivil());
                cmbEscolaridade.setSelectedIndex(paciente.getEscolaridade());
                txtConjuge.setText(paciente.getConjuge());

                for (int i = 0; i < listarConvenios.size(); i++) {
                    if (listarConvenios.get(i).getCodigo() == paciente.getConvenio().getCodigo()) {
                        cmbConvenio.setSelectedIndex(i);
                    }
                }

                cbxAph.setSelected("S".equals(paciente.getAph()));
                txtMatricula.setText(paciente.getMatricula());
                txtEndereco.setText(paciente.getEndereco());
                txtBairro.setText(paciente.getBairro());
                txtCidade.setText(paciente.getCidade());
                txtUf.setText(paciente.getUf());
                txtCep.setText(paciente.getCep());
                txtFoneFixo.setText(paciente.getFonefixo());
                txtFoneCelular.setText(paciente.getFonecelular());
                txtEmail.setText(paciente.getEmail());
                txtAnimalEstimacao.setText(paciente.getAnimalestimacao());
                txtHobby.setText(paciente.getHobby());
                cmbNivelCategoria.setSelectedIndex(paciente.getNivelcategoria());
                txtIntervalo.setText(Integer.toString(paciente.getIntervalo()));
                cmbNivelConsciencia.setSelectedIndex(paciente.getNivelconsciencia());
                cmbNivelOrientacao.setSelectedIndex(paciente.getNivelorientacao());
                cmbNivelDependencia.setSelectedIndex(paciente.getNiveldependencia());
                txtPeso.setText(Double.toString(paciente.getPeso()));
                txtAltura.setText(Double.toString(paciente.getAltura()));
                
                txtIMC.setText(Uteis.calcularImc(paciente.getAltura(), paciente.getPeso()));
                
                txtLDL.setText(paciente.getLdl());
                txtHDL.setText(paciente.getHdl());
                txtTriglicerideos.setText(paciente.getTriglicerideos());
                txtColesterolTotal.setText(paciente.getColesteroltotal());
                txtAlergia.setText(paciente.getAlergia());
                cmbDiurese.setSelectedIndex(paciente.getDiurese());
                cbxFralda.setSelected("S".equals(paciente.getFralda()));
                cmbEliminacaoIntestinal.setSelectedIndex(paciente.getEliminacaointestinal());
                cmbAlimentacao.setSelectedIndex(paciente.getAlimentacao());
                cmbAlimentacaoEnteral.setSelectedIndex(paciente.getAlimentacaoenteral());
                cmbAlimentacaoTipo.setSelectedIndex(paciente.getAlimentacaotipo());
                cmbSalgado.setSelectedIndex(retornaIndicePorNome(paciente.getAlimentacaosalgado()));
                cmbConservas.setSelectedIndex(retornaIndicePorNome(paciente.getAlimentacaoconserva()));
                cmbEnlatado.setSelectedIndex(retornaIndicePorNome(paciente.getAlimentacaoenlatado()));
                cmbIndustrializado.setSelectedIndex(retornaIndicePorNome(paciente.getAlimentacaoindustrializado()));
                cmbSaleiro.setSelectedIndex(retornaIndicePorNome(paciente.getAlimentacaosaleiro()));
                cmbSuporteOxigenio.setSelectedIndex(paciente.getSuporteoxigenio());
                cmbLesaoPele.setSelectedIndex(paciente.getLesaopele());
                cmbHistoricoQueda.setSelectedIndex(paciente.getHistoricoqueda());
                cbxFralda.setSelected("S".equals(paciente.getFralda()));
                cbxAntibiotico.setSelected("S".equals(paciente.getAntibiotico()));
                txtCircunferenciaAbdominal.setText(paciente.getCircunferenciaabdominal());
                txtGlicemiaJejum.setText(paciente.getGlicemiajejum());
                cmbMobilidade.setSelectedIndex(paciente.getMobilidade());
                cmbMobilidadeAcamado.setSelectedIndex(paciente.getMobilidadeacamado());
                txtHabitoAlimentar.setText(paciente.getHabitoalimentar());
                cmbIngestaHidrica.setSelectedIndex(paciente.getIngestahidrica());
                cmbAtividadeFisica.setSelectedIndex(paciente.getAtividadefisica());
                cmbAtividadeFisicaTipo.setSelectedIndex(retornarIndicePorTipoAtividadeFisica(paciente.getAtividadefisicatipo()));
                cmbTabagismo.setSelectedIndex(retornaIndicePorNome(paciente.getTabagismo()));
                cmbAlcoolismo.setSelectedIndex(retornaIndicePorNome(paciente.getAlcoolismo()));
                cmbConsumoAlcool.setSelectedIndex(retornaIndicePorNome(paciente.getConsumoalcool()));
                cmbDenticao.setSelectedIndex(paciente.getDenticao());
                cmbAcuidadeVisual.setSelectedIndex(paciente.getAcuidadevisual());
                cmbAcuidadeAuditiva.setSelectedIndex(paciente.getAcuidadeauditiva());
                txtIndiceLace.setText(Integer.toString(retornarIndiceLace(xcodigo)));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.toString());
        }
    }

    private void PreencheConvenio() throws SQLException {
        cmbConvenio.removeAllItems();
        ConvenioDAO daoConvenio = new ConvenioDAO();
        listarConvenios = ConvenioDAO.listarTodos("");
        for (int i = 0; i < listarConvenios.size(); i++) {
            cmbConvenio.addItem(listarConvenios.get(i));
        }
    }

    private int retornaIndicePorNome(String nome) {

        if (null == nome) {
            return -1;
        } else {
            switch (nome) {
                case "S":
                    return 0;
                case "N":
                    return 1;
                case "R":
                    return 2;
                case "I":
                    return 3;
                default:
                    return -1;
            }
        }

    }

    private String retornarNomePorIndice(int indice) {
        switch (indice) {
            case 0:
                return "S";
            case 1:
                return "N";
            case 2:
                return "R";
            case 3:
                return "I";
            default:
                return "I";
        }
    }

    private int retornarIndicePorTipoAtividadeFisica(String nome) {

        if (null == nome) {
            return 0;
        } else {
            switch (nome) {
                case "BALET":
                    return 1;
                case "BASQUETE":
                    return 2;
                case "BOXE":
                    return 3;
                case "CAMINHADA":
                    return 4;
                case "CAPOEIRA":
                    return 5;
                case "CICLISMO":
                    return 6;
                case "CORRIDA":
                    return 7;
                case "DANÇA":
                    return 8;
                case "DAN&Ccedil;A":
                    return 8;
                case "FUTEBOL":
                    return 9;
                case "FUTSAL":
                    return 10;
                case "HANDEBOL":
                    return 11;
                case "JIU JITSU":
                    return 12;
                case "JUDÔ":
                    return 13;
                case "JUD&Ocirc;":
                    return 13;
                case "KARATÊ":
                    return 14;
                case "KARAT&Ecirc;":
                    return 14;
                case "MMA":
                    return 15;
                case "MOTOCROSS":
                    return 16;
                case "MUAY THAI":
                    return 17;
                case "MUSCULAÇÃO":
                    return 18;
                case "MUSCULA&Ccedil;&Atilde;O":
                    return 18;
                case "NATAÇÃO":
                    return 19;
                case "NATAÃ‡ÃƒO":
                    return 19;
                case "PATINAÇÃO":
                    return 20;
                case "PATINA&Ccedil;&Atilde;O":
                    return 20;
                case "SKATE":
                    return 21;
                case "SURF":
                    return 22;
                case "TÊNIS":
                    return 23;
                case "T&Ecirc;NIS":
                    return 23;
                case "TRIATLON":
                    return 24;
                case "TRILHA":
                    return 25;
                case "VOLEIBOL":
                    return 26;
                default:
                    return 0;
            }
        }

    }

    private int retornarIndiceLace(int codpaciente) throws SQLException {
        return daoPacienteInternacao.retornarUltimoIndiceLace(codpaciente);
    }

    private void gravar() throws SQLException {
        Paciente p = new Paciente();
        p.setCodigo(xcodigo);
        p.setNome(txtNome.getText());
        p.setNascimento(txtNascimento.getText());
        p.setSexo(cmbSexo.getSelectedIndex());
        p.setEstadocivil(cmbEstadoCivil.getSelectedIndex());
        p.setConjuge(txtConjuge.getText());
        p.setConvenio(((Convenio)cmbConvenio.getSelectedItem()));
        p.setEndereco(txtEndereco.getText());
        p.setBairro(txtBairro.getText());
        p.setCidade(txtCidade.getText());
        p.setUf(txtUf.getText());
        p.setCep(txtCep.getText());
        p.setFonefixo(txtFoneFixo.getText());
        p.setAnimalestimacao(txtAnimalEstimacao.getText());
        p.setIntervalo(Integer.parseInt(txtIntervalo.getText()));
        p.setAph(cbxAph.isSelected() ? "S" : "N");
        p.setApelido(txtApelido.getText());
        p.setNivelconsciencia(cmbNivelConsciencia.getSelectedIndex());
        p.setNivelorientacao(cmbNivelOrientacao.getSelectedIndex());
        p.setAlergia(txtAlergia.getText());
        p.setAlimentacao(cmbAlimentacao.getSelectedIndex());
        p.setAlimentacaoenteral(cmbAlimentacaoEnteral.getSelectedIndex());
        p.setAlimentacaotipo(cmbAlimentacaoTipo.getSelectedIndex());
        p.setDiurese(cmbDiurese.getSelectedIndex());
        p.setEliminacaointestinal(cmbEliminacaoIntestinal.getSelectedIndex());
        p.setSuporteoxigenio(cmbSuporteOxigenio.getSelectedIndex());
        p.setLesaopele(cmbLesaoPele.getSelectedIndex());
        p.setHistoricoqueda(cmbHistoricoQueda.getSelectedIndex());
        p.setFratura(cbxFratura.isSelected() ? "S" : "N");
        p.setEmail(txtEmail.getText());
        p.setFonecelular(txtFoneCelular.getText());
        p.setFralda(cbxFralda.isSelected() ? "S" : "N");
        p.setAntibiotico(cbxAntibiotico.isSelected() ? "S" : "N");
        p.setMobilidade(cmbMobilidade.getSelectedIndex());
        p.setMobilidadeacamado(cmbMobilidadeAcamado.getSelectedIndex());
        p.setHabitoalimentar(txtHabitoAlimentar.getText());
        p.setIngestahidrica(cmbIngestaHidrica.getSelectedIndex());
        p.setAtividadefisica(cmbAtividadeFisica.getSelectedIndex());
        p.setAtividadefisicatipo(cmbAtividadeFisicaTipo.getSelectedItem().toString());
        p.setTabagismo(retornarNomePorIndice(cmbTabagismo.getSelectedIndex()));
        p.setAlcoolismo(retornarNomePorIndice(cmbAlcoolismo.getSelectedIndex()));
        p.setDenticao(cmbDenticao.getSelectedIndex());
        p.setAcuidadevisual(cmbAcuidadeVisual.getSelectedIndex());
        p.setAcuidadeauditiva(cmbAcuidadeAuditiva.getSelectedIndex());
        p.setPeso(Double.parseDouble(txtPeso.getText()));
        p.setAltura(Double.parseDouble(txtAltura.getText()));
        p.setMatricula(txtMatricula.getText());
        p.setHobby(txtHobby.getText());
        p.setNiveldependencia(cmbNivelDependencia.getSelectedIndex());
        p.setAlimentacaosalgado(retornarNomePorIndice(cmbSalgado.getSelectedIndex()));
        p.setAlimentacaoconserva(retornarNomePorIndice(cmbConservas.getSelectedIndex()));
        p.setAlimentacaoenlatado(retornarNomePorIndice(cmbEnlatado.getSelectedIndex()));
        p.setAlimentacaoindustrializado(retornarNomePorIndice(cmbIndustrializado.getSelectedIndex()));
        p.setAlimentacaosaleiro(retornarNomePorIndice(cmbSaleiro.getSelectedIndex()));
        p.setGlicemiajejum(txtGlicemiaJejum.getText());
        p.setCircunferenciaabdominal(txtCircunferenciaAbdominal.getText());
        p.setConsumoalcool(retornarNomePorIndice(cmbConsumoAlcool.getSelectedIndex()));
        p.setEscolaridade(cmbEscolaridade.getSelectedIndex());
        p.setNivelcategoria(cmbNivelCategoria.getSelectedIndex());
        p.setLdl(txtLDL.getText());
        p.setHdl(txtHDL.getText());
        p.setTriglicerideos(txtTriglicerideos.getText());
        p.setColesteroltotal(txtColesterolTotal.getText());
        PacienteDAO.validaDados(p);
    }
}
