/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sr_alocuidador.views.cadastros;

import br.com.sr_alocuidador.daos.ConvenioDAO;
import br.com.sr_alocuidador.helpers.Uteis;
import br.com.sr_alocuidador.models.Convenio;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author plima
 */
public class frmConvenioCad extends javax.swing.JDialog {

    public int xcodigo;
    private ConvenioDAO convenioDAO;

    /**
     * Creates new form frmConvenioCad
     */
    public frmConvenioCad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRazaoSocial = new javax.swing.JLabel();
        txtRazaoSocial = new javax.swing.JTextField();
        lblNomeFantasia = new javax.swing.JLabel();
        txtNomeFantasia = new javax.swing.JTextField();
        lblCnpj = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JTextField();
        lblInscricaoEstadual = new javax.swing.JLabel();
        txtInscricaoEstadual = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblUf = new javax.swing.JLabel();
        txtUf = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        lblContato = new javax.swing.JLabel();
        txtContatos = new javax.swing.JTextField();
        btnGravar = new javax.swing.JButton();
        lblVrCobranca = new javax.swing.JLabel();
        txtVrCobranca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Convênio");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRazaoSocial.setText("Razão Social:");
        getContentPane().add(lblRazaoSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        getContentPane().add(txtRazaoSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 520, -1));

        lblNomeFantasia.setText("Nome Fantasia:");
        getContentPane().add(lblNomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));
        getContentPane().add(txtNomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 350, -1));

        lblCnpj.setText("CNPJ:");
        getContentPane().add(lblCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        getContentPane().add(txtCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 230, -1));

        lblInscricaoEstadual.setText("Inscrição Estadual:");
        getContentPane().add(lblInscricaoEstadual, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));
        getContentPane().add(txtInscricaoEstadual, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 230, -1));

        lblEndereco.setText("Endereço:");
        getContentPane().add(lblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        getContentPane().add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 520, -1));

        lblBairro.setText("Bairro:");
        getContentPane().add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));
        getContentPane().add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 350, -1));

        lblCidade.setText("Cidade:");
        getContentPane().add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        getContentPane().add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 350, -1));

        lblUf.setText("UF:");
        getContentPane().add(lblUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));
        getContentPane().add(txtUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 90, -1));

        lblCep.setText("CEP:");
        getContentPane().add(lblCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));
        getContentPane().add(txtCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 150, -1));

        lblContato.setText("Contatos:");
        getContentPane().add(lblContato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));
        getContentPane().add(txtContatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 880, -1));

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        lblVrCobranca.setText("Valor para cobrança:");
        getContentPane().add(lblVrCobranca, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, -1, -1));

        txtVrCobranca.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtVrCobranca, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 150, -1));

        setSize(new java.awt.Dimension(987, 419));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        convenioDAO = new ConvenioDAO();
        pesquisar();
        txtRazaoSocial.grabFocus();
    }//GEN-LAST:event_formWindowOpened

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        if (validaDados()) {
            gravar();
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConvenioCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConvenioCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConvenioCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConvenioCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmConvenioCad dialog = new frmConvenioCad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void pesquisar() {
        try {
            DecimalFormat df = new DecimalFormat("#,###.00");
            
            Convenio convenio = convenioDAO.buscarPorId(xcodigo);
            if (convenio != null) {
                txtRazaoSocial.setText(convenio.getRazaosocial());
                txtNomeFantasia.setText(convenio.getNomefantasia());
                txtCnpj.setText(convenio.getCnpj());
                txtInscricaoEstadual.setText(convenio.getInscricaoestadual());
                txtEndereco.setText(convenio.getEndereco());
                txtBairro.setText(convenio.getBairro());
                txtCidade.setText(convenio.getCidade());
                txtUf.setText(convenio.getUf());
                txtCep.setText(convenio.getCep());
                txtContatos.setText(convenio.getContatos());
                txtVrCobranca.setText(df.format(convenio.getVrcobranca()));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro de sql: " + ex.toString());
        }
    }

    private boolean validaDados() {
        if ("".equals(txtRazaoSocial.getText())) {
            JOptionPane.showMessageDialog(null, "Razão não informado");
            txtRazaoSocial.grabFocus();
            return false;
        } else if ("".equals(txtNomeFantasia.getText())) {
            JOptionPane.showMessageDialog(null, "Nome fantasia não informado");
            txtNomeFantasia.grabFocus();
            return false;
        } else if ("".equals(txtCnpj.getText())) {
            JOptionPane.showMessageDialog(null, "CNPJ não informado");
            txtCnpj.grabFocus();
            return false;
        } else if ("".equals(txtEndereco.getText())) {
            JOptionPane.showMessageDialog(null, "Endereço não informado");
            txtEndereco.grabFocus();
            return false;
        } else if ("".equals(txtBairro.getText())) {
            JOptionPane.showMessageDialog(null, "Bairro não informado");
            txtBairro.grabFocus();
            return false;
        } else if ("".equals(txtCidade.getText())) {
            JOptionPane.showMessageDialog(null, "Cidade não informada");
            txtCidade.grabFocus();
            return false;
        } else if ("".equals(txtUf.getText())) {
            JOptionPane.showMessageDialog(null, "UF não informado");
            txtUf.grabFocus();
            return false;
        } else if ("".equals(txtCep.getText())) {
            JOptionPane.showMessageDialog(null, "CEP não informado");
            txtCep.grabFocus();
            return false;
        } else if ("".equals(txtContatos.getText())) {
            JOptionPane.showMessageDialog(null, "Contato não informado");
            txtContatos.grabFocus();
            return false;
        } else if (!Uteis.isCNPJ(txtCnpj.getText())) {
            JOptionPane.showMessageDialog(null, "CNPJ inválido");
            txtCnpj.grabFocus();
            return false;
        } else if ("".equals(txtVrCobranca.getText())) {
            JOptionPane.showMessageDialog(null, "Valor para cobrança não informado.");
            txtVrCobranca.grabFocus();
            return false;
        } else {
            return true;
        }
    }

    private void gravar() {
        Convenio convenio = new Convenio();
        convenio.setCodigo(xcodigo);
        convenio.setRazaosocial(txtRazaoSocial.getText());
        convenio.setNomefantasia(txtNomeFantasia.getText());
        convenio.setCnpj(txtCnpj.getText());
        convenio.setInscricaoestadual(txtInscricaoEstadual.getText());
        convenio.setEndereco(txtEndereco.getText());
        convenio.setBairro(txtBairro.getText());
        convenio.setCidade(txtCidade.getText());
        convenio.setUf(txtUf.getText());
        convenio.setCep(txtCep.getText());
        convenio.setContatos(txtContatos.getText());
        convenio.setVrcobranca(Double.parseDouble(txtVrCobranca.getText().replaceAll("\\.", "").replaceAll(",", ".")));
        try {
            convenioDAO.ValidaDados(convenio);
            JOptionPane.showMessageDialog(null, "Registro gravado com sucesso.");
            this.setVisible(false);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro de sql: " + ex.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGravar;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblContato;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblInscricaoEstadual;
    private javax.swing.JLabel lblNomeFantasia;
    private javax.swing.JLabel lblRazaoSocial;
    private javax.swing.JLabel lblUf;
    private javax.swing.JLabel lblVrCobranca;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtContatos;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtInscricaoEstadual;
    private javax.swing.JTextField txtNomeFantasia;
    private javax.swing.JTextField txtRazaoSocial;
    private javax.swing.JTextField txtUf;
    private javax.swing.JTextField txtVrCobranca;
    // End of variables declaration//GEN-END:variables
}
