/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sr_alocuidador.views.cadastros;

import br.com.sr_alocuidador.daos.PerguntaItemDAO;
import br.com.sr_alocuidador.models.PerguntaItem;
import br.com.sr_alocuidador.helpers.Uteis;
import br.com.sr_alocuidador.models.Pergunta;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author plima
 */
public class frmPerguntaItemPesq extends javax.swing.JDialog {

    private PerguntaItemDAO daoPerguntaItem;
    public Pergunta xpergunta;
    
    public frmPerguntaItemPesq(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdicionar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultado = new javax.swing.JTable();
        btnOpcao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pergunta");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnAdicionar.setText("Novo");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Opção"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResultadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblResultado);
        if (tblResultado.getColumnModel().getColumnCount() > 0) {
            tblResultado.getColumnModel().getColumn(0).setMinWidth(0);
            tblResultado.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblResultado.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        btnOpcao.setText("Opção");
        btnOpcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1174, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpcao)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnOpcao))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1216, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        daoPerguntaItem = new PerguntaItemDAO();
        try {
            pesquisar();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro encontrado: " + ex.toString());
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        try {
            incluir();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro encontrado: " + ex.toString());
        }
        
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (Uteis.linhaSelecionada(tblResultado)){
            try {
                alterar();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro encontrado: " + ex.toString());
            }            
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja excluir o registro?", "Exclusão", JOptionPane.YES_NO_OPTION);
        if (resposta == 0){
            try {
                excluir();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro encontrado: " + ex.toString());
            }
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tblResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultadoMouseClicked
        if (evt.getClickCount() > 1){
            try {
                alterar();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro encontrado: " + ex.toString());
            }
        }
    }//GEN-LAST:event_tblResultadoMouseClicked

    private void btnOpcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcaoActionPerformed
        abrirOpcoes();
    }//GEN-LAST:event_btnOpcaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPerguntaItemPesq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPerguntaItemPesq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPerguntaItemPesq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPerguntaItemPesq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPerguntaItemPesq dialog = new frmPerguntaItemPesq(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnOpcao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResultado;
    // End of variables declaration//GEN-END:variables

    private void pesquisar() throws SQLException {
        
        DefaultTableModel modelo = (DefaultTableModel)tblResultado.getModel();
        modelo.setNumRows(0);
        for(PerguntaItem p : daoPerguntaItem.ListarDados(xpergunta.getCodigo())){
            modelo.addRow(new Object[]{ p.getCodigo(), p.getNome(), "P".equals(p.getOpcao()) ? "PERGUNTA" : "A".equals(p.getOpcao()) ? "ALERTA" : "" });
        }
        
    }
    
    private void incluir() throws SQLException{
        
        frmPerguntaItemCad f = new frmPerguntaItemCad(null, rootPaneCheckingEnabled);
        f.xcodigo = 0;
        f.xpergunta = xpergunta;
        f.setTitle(this.getTitle());
        f.setVisible(true);
        pesquisar();
        
    }
    
    private void alterar() throws SQLException{
        
        if (Uteis.linhaSelecionada(tblResultado)){        
            frmPerguntaItemCad f = new frmPerguntaItemCad(null, rootPaneCheckingEnabled);
            f.xcodigo = Integer.parseInt(tblResultado.getValueAt(tblResultado.getSelectedRow(), 0).toString());
            f.xpergunta = xpergunta;
            f.setTitle(this.getTitle());
            f.setVisible(true);
            pesquisar();
        }
        
    }
    
    private void excluir() throws SQLException{
        
        if (Uteis.linhaSelecionada(tblResultado)){
            daoPerguntaItem.excluir(Integer.parseInt(tblResultado.getValueAt(tblResultado.getSelectedRow(), 0).toString()));
            pesquisar();
        }
        
    }

    private void abrirOpcoes() {
        
        if (Uteis.linhaSelecionada(tblResultado)){
            String opcao = tblResultado.getValueAt(tblResultado.getSelectedRow(), 2).toString();
            
            if ("PERGUNTA".equals(opcao)){
                frmPerguntaItemPerguntaCad f = new frmPerguntaItemPerguntaCad(null, rootPaneCheckingEnabled);
                f.xcoditem = Integer.parseInt(tblResultado.getValueAt(tblResultado.getSelectedRow(), 0).toString());
                f.setTitle("Sub-Perguntas do item " + tblResultado.getValueAt(tblResultado.getSelectedRow(), 1).toString());
                f.setVisible(true);
            }
            else if ("ALERTA".equals(opcao)){
                try{
                    frmPerguntaItemAlertaPesq f = new frmPerguntaItemAlertaPesq(null, rootPaneCheckingEnabled);
                    f.xpergitem = daoPerguntaItem.BuscarPorId( Integer.parseInt(tblResultado.getValueAt(tblResultado.getSelectedRow(), 0).toString()) );
                    f.setTitle("Alertas do item " + tblResultado.getValueAt(tblResultado.getSelectedRow(), 1).toString());
                    f.setVisible(true);
                }catch(SQLException ex){
                    JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
                }
            }
            else 
                JOptionPane.showMessageDialog(null, "Nenhuma opção foi informada");
        }
        
    }
}
